project:
  type: website

website:
  repo-url: https://github.com/metzger-chambon/singlecellviz
  repo-actions: [edit, issue]
  title: "SingleCellViz doc"
  site-url: "https:/metzger-chambon.igbmc.science/SingleCellViz/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - usage.qmd
      - development.qmd
      - deployment.qmd
      - about.qmd

  page-footer: 
      border: true
      left: "Metzger-Chambon, IGBMC" 
      right: 
      - icon: github
        href: https://github.com/metzger-chambon/singlecellviz
      - icon: link
        href: https://metzger-chambon.igbmc.science/SingleCellViz/

        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



